
import { LIKE, DISLIKE, REAL_TIME, COMMENT, DELETE_COMMENT, CREATE_POST, DELETE_POST } from "./posts";
import { LOGIN, LOGOUT,UPDATE_INFOUSER } from "./user";
import { ADD_USER, REMOVE_USER } from "./users";



const action = {
    ADD_USER: ADD_USER,
    REMOVE_USER: REMOVE_USER,
    LOGIN: LOGIN,
    LOGOUT: LOGOUT,
    UPDATE_INFOUSER: UPDATE_INFOUSER,
    LIKE: LIKE,
    DISLIKE: DISLIKE,
    REAL_TIME: REAL_TIME,
    COMMENT: COMMENT,
    DELETE_COMMENT: DELETE_COMMENT,
    CREATE_POST: CREATE_POST,
    DELETE_POST: DELETE_POST
}

export default action